name: a

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - run: echo "Hello, ${{ github.actor }}" > a.txt
      - uses: actions/upload-artifact@v4
        with:
          name: a
          path: a.txt
